#Numpy
Numpy gjør at vi kan ta i bruk multi-deminsional arrays og mattematiske funksjoner som lett lar oss gjennomføre lineær algebra kalkulasjoner. 

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
#Finner gjennomsnittelig avkasting på et portfolio
stock_list = [2.6, 1.2, 3.3, 8, 4.1] #liste
#Vi lager et numpy array på følgende måte:
returns = np.array(stock_list)
print("Returns: {0}, and is of type {1}".format(returns, type(returns)))

Returns: [2.6 1.2 3.3 8.  4.1], and is of type <class 'numpy.ndarray'>


In [0]:
returns

array([2.6, 1.2, 3.3, 8. , 4.1])

In [0]:
#2-dimensjonalt array
two_d = np.array([[1,2], [3,4]])
print(two_d)

[[1 2]
 [3 4]]


In [0]:
#Shape ghir oss dimensjonene på arrayet
print(two_d.shape)

(2, 2)


In [0]:
#Man er i stand til å slice arrayene på vanlig måte
print(returns[1:3])
print("_______")
print(two_d)
print(two_d[:, 0]) #første kolonne
print(two_d[0,:]) #første rad

[1.2 3.3]
_______
[[1 2]
 [3 4]]
[1 3]
[1 2]


In [0]:
#Man har også mange array funksjoner.
print(returns)
print("Log:", np.log(returns)) #Log all numbers
print("Mean:", np.mean(returns))
print("Max:", np.max(returns))


[2.6 1.2 3.3 8.  4.1]
Log: [0.95551145 0.18232156 1.19392247 2.07944154 1.41098697]
Mean: 3.84
Max: 8.0


In [0]:
#kan også modifisere arrayene ganske fort
returns2 = returns*10
print(returns)
print(returns2)

[2.6 1.2 3.3 8.  4.1]
[26. 12. 33. 80. 41.]


In [0]:
def devide3(arr):
  return arr/3

test1 = devide3(returns2)
print(test1)

[ 8.66666667  4.         11.         26.66666667 13.66666667]
